
create table client 
( id_client number generated by default on null as identity start with 1 increment by 1,
  full_name varchar(50) not null,
  mobile varchar(20) not null,
  address varchar(100) not null,
  passport varchar(20) not null,
  unique(passport),
  constraint id_client_pk primary key(id_client) 
)tablespace tblspc_a;
 


drop table client

create table employee
( id_employee number generated by default on null as identity start with 1 increment by 1,
  surname varchar(20) not null,
  name varchar(20) not null,
  second_name varchar(20) not null,
  post varchar(50) not null,
  date_of_birth date not null,
  date_of_hiring date not null,
  address varchar(100) not null,
  mobile varchar(15) not null,
  salary number(20) not null,
  constraint id_employee_pk primary key(id_employee)
) tablespace tblspc_e;

drop table employee

create table realty
( id_realty number generated by default on null as identity start with 1 increment by 1,
  id_owner number,
  type_of_realty varchar(20) check(type_of_realty in ('квартира','дом','земельный участок')) not null,
  type_of_transaction varchar(20) check(type_of_transaction in ('аренда','продажа')) not null,
  district varchar(20) not null,
  address varchar(200) not null,
  price number(10,2) not null,
  constraint id_realty_pk primary key(id_realty),
  constraint id_owner_fk foreign key(id_owner) references client(id_client)
)tablespace tblspc_a;

drop table realty

create table deal
( id_deal number generated by default on null as identity start with 1 increment by 1,
  id_realty number not null unique,
  id_employee number not null,
  seller number not null,
  buyer number not null,
  date_of_deal date not null,
  sum_of_deal number(10,2) not null,
  constraint id_deal_pk primary key(id_deal),
  constraint id_realty_fk foreign key(id_realty) references realty(id_realty),
  constraint id_employee_fk foreign key(id_employee) references employee(id_employee),
  constraint id_seller_fk foreign key(seller) references client(id_client),
  constraint id_buyer_fk foreign key(buyer) references client(id_client)
)tablespace tblspc_a;

drop table deal


create table apartment
( id_apartment number,
  number_of_rooms number not null,
  square number(10,2) not null,
  building_material varchar(20),
  year_of_construction number not null,
  floor number not null,
  constraint id_apartment_pk primary key(id_apartment),
  constraint id_apartment_fk foreign key(id_apartment) references realty(id_realty)
) tablespace tblspc_a;

drop table apartment

create table house
( id_house number,
  number_of_rooms number not null,
  number_of_floors number not null,
  land_area number(10,2) not null,
  house_area number(10,2) not null,
  building_material varchar(20),
  year_of_construction number not null,
  constraint id_house_pk primary key(id_house),
  constraint id_house_fk foreign key(id_house) references realty(id_realty)
)tablespace tblspc_a;

drop table house

create table land_plot
( id_land_plot number,
  area number(10,2) not null,
  constraint id_land_plot_pk primary key(id_land_plot),
  constraint id_land_plot_fk foreign key(id_land_plot) references realty(id_realty)
)tablespace tblspc_a;

drop table land_plot

-------------------------employee

select * from employee

insert into employee(surname, name, second_name, post,  date_of_birth, date_of_hiring, address, mobile, salary)
            values('Огурцова', 'Александра', 'Андреевна', 'директор', '20/02/2001', '07/09/2020', 'Минск Корженевского 31-115', '+375336960657', 1450);
            
insert into employee(surname, name, second_name, post,  date_of_birth, date_of_hiring, address, mobile, salary)
            values('Береснева', 'Екатерина', 'Юрьевна', 'риэлтор', '20/02/2001', '07/09/2020', 'Минск Белорусская 21-113а', '+375336960625', 1100);
            
insert into employee(surname, name, second_name, post,  date_of_birth, date_of_hiring, address, mobile, salary)
            values('Герасименко', 'Максим', 'Владиславович', 'риэлтор', '20/06/1998', '07/09/2020', 'Минск Казинца 46', '+375336477356', 1100);
            
insert into employee(surname, name, second_name, post,  date_of_birth, date_of_hiring, address, mobile, salary)
            values('Степаненко', 'Светлана', 'Анатольевна', 'агент', '20/06/1998', '07/09/2020', 'Минск Московская 78-196', '+375336477893', 900);
            
insert into employee(surname, name, second_name, post,  date_of_birth, date_of_hiring, address, mobile, salary)
            values('Кошелев', 'Виктор', 'Викторович', 'агент', '20/06/1998', '07/09/2020', 'Минск Литовская 78-196', '+375338956734', 900); 
            
            
-----------------------client

select * from client

insert into client(full_name, mobile, address, passport)
             values('Карпов Владиислав Викторович',  '11', 'Минск Павлова 97-13', 'BM67867541112');
             
insert into client(full_name, mobile, address, passport)
             values('Кулич Юлия Александровна',  '22', 'Минск Сухорева 95а-14', 'BM67867781112');
             
insert into client(full_name, mobile, address, passport)
             values('Сигулина Екатерина Викторовна', '33', 'Минск Павлова 97-8', 'BM67867673456');
             
insert into client(full_name, mobile, address, passport)
             values('Обраменко Деник Викторович',  '44', 'Витебская область Орша ул Молокова 43-79', 'BM98765435678');
             
insert into client(full_name,  mobile, address, passport)
             values('Макаров Константин Децебили', '55', 'Минск Белорусская 13-67', 'BM98765822339');


